spring.profiles.active=render
spring.application.name=businessdomain-compra
server.servlet.context-path=/compra
server.port=7015

# Las configuraciones específicas están en application-render.properties

management.endpoints.web.exposure.include=*