spring.profiles.active=render
spring.application.name=businessdomain-metodopago
server.servlet.context-path=/metodopago
server.port=7014

# Sistema de Pagos Simulado - 100% GRATUITO
payment.provider=simulado

# Las configuraciones específicas están en application-render.properties

management.endpoints.web.exposure.include=*