spring.profiles.active=render
spring.application.name=businessdomain-metodopago
server.servlet.context-path=/metodopago
server.port=7014

# Sistema de Pagos Simulado - 100% GRATUITO
payment.provider=simulado

# Las configuraciones específicas están en application-render.properties

# Configuración de Zona Horaria
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.jackson.time-zone=America/Lima

management.endpoints.web.exposure.include=*