spring.profiles.active=render
spring.application.name=businessdomain-producto
server.servlet.context-path=/producto
server.port=7013

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Las configuraciones específicas están en application-render.properties

management.endpoints.web.exposure.include=*